// import { Geist, Geist_Mono } from "next/font/google";
// import '@ant-design/v5-patch-for-react-19';

// import "../globals.css";
// import Footer from "../components/Footer";
// import Navbar from "../components/Navbar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#f2f5f7] text-black`}
//       >
//         <Navbar></Navbar>
//         <div className="lg:w-[1620px] mx-auto font-lora">
//           {children}
//           </div>
//         <Footer></Footer>
//       </body>
//     </html>
//   );
// }


import { Geist, Geist_Mono } from "next/font/google";
import '@ant-design/v5-patch-for-react-19';
import "../globals.css";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#f2f5f7] text-black`}
      >
        <Navbar />
        <main className="lg:w-[1620px] mx-auto font-lora">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
                 